export default data = [
    {
        id:2,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:1,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:3,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:4,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:5,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:6,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:7,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:8,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:9,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:10,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:11,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:12,
        vote_average:7.2,
        title:"Star Wars VIII - Les derniers Jedi",
        poster_path:"",
        original_title:"Star Wars: The Last Jedi",
        overview:"Nouvel épisode de la saga. Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de choquantes révélations sur le passé…",
        release_date:"13/12/2017",
        img:'https://images-na.ssl-images-amazon.com/images/I/71c-O3GaxLL._AC_SL1200_.jpg',
    },
    {
        id:13,
        vote_average:8.1,
        title:"La Guerre des étoiles",
        poster_path:"",
        original_title:"Star Wars",
        overview:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...",
        release_date:"25/05/1977",
        img:'http://antreducinema.fr/wp-content/uploads/2020/04/La_Guerre_des_Etoiles.png',
    },
    {
        id:14,
        vote_average:8.1,
        title:"Matrix",
        poster_path:"",
        original_title:"Matrix",
        overview:"Thomas A. Anderson, un jeune informaticien connu dans le monde du hacking sous le pseudonyme de Neo18, est contacté via son ordinateur par ce qu’il pense être un groupe de hackers. Ils lui font découvrir que le monde dans lequel il vit n’est qu’un monde virtuel dans lequel les êtres humains sont gardés inconsciemment sous contrôle.",
        release_date:"23/06/1999",
        img:'https://cineluctable.files.wordpress.com/2019/09/matrix.jpg',
    },
]
